var R=require("../chunks/ssr/[turbopack]_runtime.js")("server/app/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0sfnyqb._.js")
R.c("server/chunks/ssr/0j_w_next_dist_esm_build_templates_app-page_025u5ta.js")
R.c("server/chunks/ssr/0j_w_next_dist_0f6mz.x._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0sbahn0._.js")
R.c("server/chunks/ssr/0j_w_next_dist_0cfnini._.js")
R.c("server/chunks/ssr/0j_w_next_dist_13ostq2._.js")
R.c("server/chunks/ssr/[root-of-the-server]__00oy4-h._.js")
R.c("server/chunks/ssr/0j_w_next_dist_client_components_0vm6kgr._.js")
R.c("server/chunks/ssr/0j_w_next_dist_client_components_builtin_forbidden_00okp9x.js")
R.c("server/chunks/ssr/0j_w_next_dist_client_components_builtin_unauthorized_0-c66mp.js")
R.c("server/chunks/ssr/0j_w_next_dist_client_components_builtin_global-error_06ux9h9.js")
R.c("server/chunks/ssr/Documents_GitHub_Verisim__next-internal_server_app_page_actions_0o5xg.p.js")
R.m(8345)
module.exports=R.m(8345).exports
