var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/_not-found/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0csh2kc._.js")
R.c("server/chunks/ssr/0j_w_next_dist_esm_build_templates_app-page_0fye68l.js")
R.c("server/chunks/ssr/0j_w_next_dist_0f6mz.x._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0sbahn0._.js")
R.c("server/chunks/ssr/0j_w_next_dist_0cfnini._.js")
R.c("server/chunks/ssr/0j_w_next_dist_13ostq2._.js")
R.c("server/chunks/ssr/[root-of-the-server]__00oy4-h._.js")
R.c("server/chunks/ssr/0j_w_next_dist_client_components_0vm6kgr._.js")
R.c("server/chunks/ssr/0j_w_next_dist_client_components_builtin_forbidden_00okp9x.js")
R.c("server/chunks/ssr/0j_w_next_dist_client_components_builtin_unauthorized_0-c66mp.js")
R.c("server/chunks/ssr/0m4n_GitHub_Verisim__next-internal_server_app__not-found_page_actions_0~_102r.js")
R.m(1450)
module.exports=R.m(1450).exports
